project:
  type: website

website:
  site-url: https://lrncrd.github.io/
  #title: "Academic CV"
  sidebar: 
    style: "docked"
    search: false
    contents:
      - title: "Home"
        url: "index.qmd"
      - title: "Publications"
        url: "publications.qmd"
      - title: "CV"
        url: "cv.qmd"
      - title: "Conference Talks"
        url: "talks.qmd"
      - title: "Packages"
        url: "packages.qmd"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

